apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "rocketchat.fullname" . }}
  labels:
    app: {{ template "rocketchat.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "rocketchat.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DEPLOY_PLATFORM
            value: helm-chart
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MONGO_URL
          {{ if .Values.mongodb.mongodbUsername }}
            valueFrom:
              secretKeyRef:
                name: {{ template "rocketchat.fullname" . }}
                key: mongo-uri
          {{ else }}
            value: mongodb://{{ template "rocketchat.mongodb.fullname" . }}:27017/rocketchat
          {{ end }}
          {{ if .Values.host }}
          - name: ROOT_URL
            value: https://{{ .Values.host }}
          {{ end }}
          - name: ADMIN_USERNAME
            value: {{ .Values.rocketchat.username }}
          - name: ADMIN_PASS
            value: {{ .Values.rocketchat.password }}
          - name: ADMIN_EMAIL
            value: {{ .Values.rocketchat.email }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 60
            timeoutSeconds: 5
          volumeMounts:
          - name: rocket-data
            mountPath: /app/uploads
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
      - name: rocket-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "rocketchat.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
